<?php return array (
  'table' => 'article',
  'front' => 
  array (
    'title' => 
    array (
      'name' => '文章标题',
      'tip' => '',
      'type' => 'text',
      'options' => '',
      'joindb' => '',
      'where' => '',
      'password' => '0',
      'css' => 'input-text',
      'length' => '10',
      'mustbe' => '1',
      'search' => '0',
      'display' => '1',
      'listshow' => '1',
      'match' => '',
    ),
    'cateid' => 
    array (
      'name' => '文章类型',
      'tip' => '关联查找文章的类型',
      'type' => 'select',
      'options' => '',
      'joindb' => 'article_category',
      'where' => '1',
      'password' => '0',
      'css' => 'input-text',
      'length' => '',
      'mustbe' => '1',
      'search' => '0',
      'display' => '1',
      'listshow' => '1',
      'match' => '',
    ),
    'content' => 
    array (
      'name' => '文章内容',
      'tip' => '',
      'type' => 'editor',
      'options' => '',
      'joindb' => '',
      'where' => '',
      'password' => '0',
      'css' => '',
      'length' => '',
      'mustbe' => '0',
      'search' => '0',
      'display' => '1',
      'listshow' => '0',
      'match' => '',
    ),
    'status' => 
    array (
      'name' => '状态',
      'tip' => '',
      'type' => 'radio',
      'options' => '[待审核,0],[通过,1],[禁止,2]',
      'joindb' => '',
      'where' => '',
      'password' => '0',
      'css' => 'input-radio',
      'length' => '',
      'mustbe' => '0',
      'search' => '0',
      'display' => '1',
      'listshow' => '1',
      'match' => '',
    ),
    'note' => 
    array (
      'name' => '备注',
      'type' => 'text',
      'tip' => '',
      'value' => '',
      'password' => '0',
      'css' => 'input-text',
      'length' => '',
      'mustbe' => '0',
      'search' => '0',
      'display' => '1',
      'listshow' => '0',
      'match' => '',
    ),
    'thumb' => 
    array (
      'name' => '标题图片',
      'tip' => '',
      'type' => 'file',
      'options' => '',
      'joindb' => '',
      'where' => '',
      'password' => '0',
      'css' => 'input-text',
      'length' => '',
      'mustbe' => '0',
      'search' => '0',
      'display' => '1',
      'listshow' => '1',
      'match' => '',
    ),
    'iscomplete' => 
    array (
      'name' => '是否完成',
      'tip' => '',
      'type' => 'radio',
      'options' => '[是,1],[否,0]',
      'joindb' => '',
      'where' => '',
      'css' => '',
      'length' => '',
      'display' => '1',
      'listshow' => '0',
      'match' => '',
    ),
    'addtime' => 
    array (
      'name' => '创建时间',
      'tip' => '',
      'type' => 'auto',
      'options' => '',
      'joindb' => '',
      'where' => '',
      'function' => 'time',
      'datacreate' => '1',
      'constant' => '',
      'css' => '',
      'length' => '',
      'match' => '',
    ),
  ),
  'listtitle' => '首页，文章管理，社会关爱',
  'listsearch' => 'cateid=1',
  'contrl' => 
  array (
    '添加' => 
    array (
      'lable' => '添加',
      'ctrl' => 'Article/itemedit',
      'js' => 'article_edit',
      'icon' => '&#xe600;',
    ),
  ),
  'listctrl' => 
  array (
    '编辑' => 
    array (
      'lable' => '编辑',
      'ctrl' => 'Article/itemedit',
      'js' => 'article_edit',
      'icon' => '&#xe6df;',
    ),
    '删除' => 
    array (
      'lable' => '删除',
      'ctrl' => 'Article/itemdel',
      'js' => 'article_del',
      'icon' => '&#xe6e2;',
    ),
  ),
); ?>